/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * LyricsForm.java
 *
 * Created on Mar 9, 2012, 12:56:38 PM
 */
package subtitles;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author tharindu_DG
 */
public class LyricsFrame extends javax.swing.JFrame {

    /** Creates new form LyricsForm */
    public LyricsFrame(String artist, String song) {
        initComponents();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        handler = new LyricsHandler();
        handler.read(artist, song);
        artistTxtFld.setText(artist);
        songTxtFld.setText(song);
        String lyrics = handler.getLyrics();
        if (lyrics == null) {
            lyricsTxtArea.setText("Could Not Find Lyrics For " + song);
        } else {
            lyricsTxtArea.setText(handler.getLyrics());
            lyricsWikiLbl.setText("Visit : "+handler.getLyricsWikiLink());
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lyricsTxtArea = new javax.swing.JTextArea();
        artistTxtFld = new javax.swing.JTextField();
        lyricsSearcBtn = new javax.swing.JButton();
        songTxtFld = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lyricsWikiLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Lyrics");
        setResizable(false);

        jScrollPane1.setEnabled(false);
        jScrollPane1.setFont(new java.awt.Font("Verdana", 1, 12));

        lyricsTxtArea.setColumns(20);
        lyricsTxtArea.setFont(new java.awt.Font("Verdana", 1, 12));
        lyricsTxtArea.setRows(5);
        jScrollPane1.setViewportView(lyricsTxtArea);

        artistTxtFld.setFont(new java.awt.Font("Verdana", 1, 12));

        lyricsSearcBtn.setText("Search");
        lyricsSearcBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lyricsSearcBtnActionPerformed(evt);
            }
        });

        songTxtFld.setFont(new java.awt.Font("Verdana", 1, 12));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 12));
        jLabel1.setText("Artist");

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 12));
        jLabel2.setText("Song");

        lyricsWikiLbl.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        lyricsWikiLbl.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lyricsWikiLbl.setFocusable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(songTxtFld, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(artistTxtFld, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(lyricsSearcBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 621, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 641, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lyricsWikiLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 621, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(artistTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(songTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)))
                    .addComponent(lyricsSearcBtn))
                .addGap(7, 7, 7)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 444, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lyricsWikiLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // function called when manual lyrics is preffered
    private void lyricsSearcBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lyricsSearcBtnActionPerformed
        String artist = artistTxtFld.getText().trim();
        String song = songTxtFld.getText().trim();
        if (artist == null || song == null || artist.equals("") || song.equals("")) {
            JOptionPane.showMessageDialog(null, "Enter Artist & Song to search!");
        } else {
            // making the query and setting up the UI according to the returned data
            handler.read(artist, song);
            artistTxtFld.setText(handler.getArtistNodeText());
            songTxtFld.setText(handler.getSongNodeText());
            lyricsTxtArea.setText(handler.getLyrics());
            lyricsWikiLbl.setText("Visit : "+handler.getLyricsWikiLink());
        }
    }//GEN-LAST:event_lyricsSearcBtnActionPerformed
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField artistTxtFld;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton lyricsSearcBtn;
    private javax.swing.JTextArea lyricsTxtArea;
    private javax.swing.JLabel lyricsWikiLbl;
    private javax.swing.JTextField songTxtFld;
    // End of variables declaration//GEN-END:variables
    private LyricsHandler handler;
}
